# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14P9jyRnsuUnrRyN2OwFQd7gMjc2TVVfR
"""

import streamlit as st
import pandas as pd
import joblib

# Load trained model
model = joblib.load("career_prediction_model.pkl")

st.set_page_config(page_title="AI Career Prediction", layout="centered")

st.title("🎓 AI-Based Career Prediction System")
st.write("Enter your skill details below to get career recommendation.")

# -------- USER INPUTS -------- #

hours = st.slider("Hours working per day", 0, 12, 6)
logical = st.slider("Logical quotient rating (0-5)", 0, 5, 3)
hackathons = st.slider("Hackathons participated", 0, 10, 1)
coding = st.slider("Coding skills rating (0-5)", 0, 5, 3)
public = st.slider("Public speaking points (0-5)", 0, 5, 2)
self_learning = st.selectbox("Self-learning capability?", [0, 1])
certifications = st.slider("Certifications count", 0, 10, 1)
workshops = st.slider("Workshops attended", 0, 10, 1)
reading = st.slider("Reading & Writing Skills (0-5)", 0, 5, 3)
memory = st.slider("Memory capability score (0-5)", 0, 5, 3)
management = st.selectbox("Management or Technical (0=Management, 1=Technical)", [0, 1])
teamwork = st.selectbox("Worked in teams ever?", [0, 1])
introvert = st.selectbox("Introvert?", [0, 1])

# -------- PREDICTION -------- #

if st.button("🔮 Predict Career"):

    input_data = pd.DataFrame([[hours, logical, hackathons, coding, public,
                                self_learning, certifications, workshops,
                                reading, memory, management, teamwork, introvert]],
                               columns=['Hours working per day',
                                        'Logical quotient rating',
                                        'hackathons',
                                        'coding skills rating',
                                        'public speaking points',
                                        'self-learning capability?',
                                        'certifications',
                                        'workshops',
                                        'reading and writing skills',
                                        'memory capability score',
                                        'Management or Technical',
                                        'worked in teams ever?',
                                        'Introvert'])

    prediction = model.predict(input_data)
    probabilities = model.predict_proba(input_data)

    st.success(f"🎯 Recommended Career Path: {prediction[0]}")

    # -------- WOW FACTOR: Probability Display -------- #
    st.subheader("📊 Career Prediction Probability")

    prob_df = pd.DataFrame(probabilities, columns=model.classes_)
    st.bar_chart(prob_df.T)

    # -------- WOW FACTOR: Skill Readiness Score -------- #
    readiness_score = int((coding + logical + reading + memory) / 20 * 100)
    st.subheader("📈 Career Readiness Score")
    st.progress(readiness_score)
    st.write(f"Overall Readiness: {readiness_score}%")

    # -------- Personalized Action Plan -------- #
    st.subheader("📌 Personalized Action Plan")

    if coding < 3:
        st.write("• Improve coding skills by building projects.")
    if public < 3:
        st.write("• Practice communication and public speaking.")
    if logical < 3:
        st.write("• Improve logical thinking and problem solving.")
    if certifications < 2:
        st.write("• Complete relevant certifications.")
    if teamwork == 0:
        st.write("• Participate in team-based activities.")

    st.write("• Stay consistent and keep upgrading your skills.")